import { useEffect, useState, type FormEvent } from 'react'
import { Link, useNavigate } from 'react-router-dom'
import { ApiError } from '../../api/apiClient'
import { descargarArchivo, exportarReporteAtenciones, obtenerReporteAtenciones } from '../../api/reportesApi'
import type { EstadoReserva, ReporteAtencionesFiltros, ReporteAtencionesResponse, ResultadoAtencion } from '../../types'
import { dateTime, DateRangeFilter, EmptyReport, parseDate, ReportKpi, ReportLoading, ReportPagination, ReservationBadge, SelectFilter, shortDate, validateRange, type SelectOption } from './ReportShared'

const states: { id: EstadoReserva; nombre: string }[] = [{ id: 'Confirmada', nombre: 'Confirmada' }, { id: 'Reprogramada', nombre: 'Reprogramada' }, { id: 'Presente', nombre: 'Presente' }, { id: 'EnAtencion', nombre: 'En atención' }, { id: 'Atendida', nombre: 'Atendida' }, { id: 'NoAsistio', nombre: 'No asistió' }]
const results: { id: ResultadoAtencion; nombre: string }[] = [{ id: 'Completada', nombre: 'Completada' }, { id: 'Parcial', nombre: 'Parcial' }, { id: 'Interrumpida', nombre: 'Interrumpida' }]
function defaultRange() { const hasta = new Date(); const desde = new Date(hasta); desde.setDate(desde.getDate() - 29); const local = (date: Date) => new Date(date.getTime() - date.getTimezoneOffset() * 60_000).toISOString().slice(0, 10); return { fechaDesde: local(desde), fechaHasta: local(hasta) } }
const initial = (organizacionId: string): ReporteAtencionesFiltros => ({ ...defaultRange(), organizacionId, pagina: 1, tamanoPagina: 10 })
const realTime = (value?: string | null) => value ? dateTime.format(new Date(value)) : '—'

export function AttentionsReport({ organizacionId, sedes, profesionales, servicios }: { organizacionId: string; sedes: SelectOption[]; profesionales: SelectOption[]; servicios: SelectOption[] }) {
  const navigate = useNavigate(); const [draft, setDraft] = useState(() => initial(organizacionId)); const [applied, setApplied] = useState(() => initial(organizacionId)); const [data, setData] = useState<ReporteAtencionesResponse>(); const [loading, setLoading] = useState(true); const [exporting, setExporting] = useState(false); const [error, setError] = useState(''); const [validation, setValidation] = useState('')
  useEffect(() => { const next = initial(organizacionId); setDraft(next); setApplied(next) }, [organizacionId])
  useEffect(() => { const controller = new AbortController(); setLoading(true); setError(''); obtenerReporteAtenciones(applied, controller.signal).then(setData).catch(caught => { if (controller.signal.aborted) return; if (caught instanceof ApiError && caught.status === 403) return navigate('/acceso-denegado', { replace: true }); setError(caught instanceof Error ? caught.message : 'No se pudo cargar el reporte de atenciones.') }).finally(() => { if (!controller.signal.aborted) setLoading(false) }); return () => controller.abort() }, [applied, navigate])
  const set = <K extends keyof ReporteAtencionesFiltros>(key: K, value: ReporteAtencionesFiltros[K]) => setDraft(current => ({ ...current, [key]: value }))
  function apply(event: FormEvent) { event.preventDefault(); const message = validateRange(draft.fechaDesde, draft.fechaHasta); setValidation(message); if (!message) setApplied({ ...draft, pagina: 1 }) }
  function clear() { const next = initial(organizacionId); setDraft(next); setValidation(''); setApplied(next) }
  async function exportCsv() { setExporting(true); setError(''); try { const file = await exportarReporteAtenciones(applied); descargarArchivo(file.blob, file.filename ?? `reporte-atenciones-${applied.fechaDesde}-${applied.fechaHasta}.csv`) } catch (caught) { if (caught instanceof ApiError && caught.status === 403) return navigate('/acceso-denegado', { replace: true }); setError(caught instanceof ApiError && caught.status === 409 ? 'El reporte contiene demasiados registros. Reduce el rango o aplica más filtros.' : caught instanceof Error ? caught.message : 'No se pudo exportar el reporte.') } finally { setExporting(false) } }
  return <div className="reports-section"><form className="report-filters" onSubmit={apply}><DateRangeFilter desde={draft.fechaDesde} hasta={draft.fechaHasta} onDesde={value => set('fechaDesde', value)} onHasta={value => set('fechaHasta', value)} /><SelectFilter label="Sede" value={draft.sedeId} options={sedes} emptyLabel="Todas las sedes" onChange={value => set('sedeId', value || undefined)} /><SelectFilter label="Profesional" value={draft.profesionalId} options={profesionales} emptyLabel="Todos los profesionales" onChange={value => set('profesionalId', value || undefined)} /><SelectFilter label="Servicio" value={draft.servicioId} options={servicios} emptyLabel="Todos los servicios" onChange={value => set('servicioId', value || undefined)} /><SelectFilter label="Estado" value={draft.estado} options={states} emptyLabel="Todos los estados" onChange={value => set('estado', value as EstadoReserva || '')} /><SelectFilter label="Resultado" value={draft.resultado} options={results} emptyLabel="Todos los resultados" onChange={value => set('resultado', value as ResultadoAtencion || '')} />{validation ? <p className="report-validation">{validation}</p> : null}<div className="report-filter-actions"><button className="btn btn-primary" disabled={loading}>Aplicar filtros</button><button type="button" className="btn btn-outline-secondary" onClick={clear}>Limpiar</button><button type="button" className="btn btn-outline-success" disabled={exporting || loading} onClick={() => void exportCsv()}>{exporting ? 'Generando archivo...' : 'Exportar CSV'}</button></div></form>
    {error ? <div className="alert alert-danger" role="alert">{error}</div> : null}{loading ? <ReportLoading /> : data ? <><div className="report-kpis"><ReportKpi label="Reservas programadas" value={data.indicadores.reservasProgramadas} /><ReportKpi label="Atendidas" value={data.indicadores.atendidas} /><ReportKpi label="No asistieron" value={data.indicadores.noAsistieron} /><ReportKpi label="Parciales/interrumpidas" value={data.indicadores.atencionParcialInterrumpida} /><ReportKpi label="Asistencia" value={data.indicadores.sinDatos || data.indicadores.porcentajeAsistencia == null ? '—' : `${data.indicadores.porcentajeAsistencia.toLocaleString('es-PE')} %`} help={data.indicadores.sinDatos ? 'Sin datos suficientes' : undefined} /></div>
      {data.elementos.length === 0 ? <EmptyReport>No se encontraron atenciones para los filtros seleccionados.</EmptyReport> : <article className="report-card"><div className="report-table-wrap"><table className="table table-hover report-table"><thead><tr><th>Código</th><th>Fecha</th><th>Hora</th><th>Cliente</th><th>Servicio</th><th>Profesional</th><th>Llegada</th><th>Inicio real</th><th>Fin real</th><th>Duración</th><th>Resultado</th><th>Estado</th><th /></tr></thead><tbody>{data.elementos.map(item => <tr key={item.reservaId}><td>{item.codigoReserva}</td><td>{shortDate.format(parseDate(item.fecha))}</td><td>{item.horaProgramada.slice(0, 5)}</td><td>{item.cliente}</td><td>{item.servicio}</td><td>{item.profesional ?? '—'}</td><td>{realTime(item.horaLlegada)}</td><td>{realTime(item.horaInicioReal)}</td><td>{realTime(item.horaFinReal)}</td><td>{item.duracionRealMinutos == null ? '—' : `${item.duracionRealMinutos} min`}</td><td>{item.resultado ?? '—'}</td><td><ReservationBadge status={item.estado} /></td><td><Link className="btn btn-sm btn-outline-primary" to={`/organizaciones/${organizacionId}/reservas/${item.reservaId}/atencion`}>Ver atención</Link></td></tr>)}</tbody></table></div><div className="report-mobile-list">{data.elementos.map(item => <article className="report-card report-mobile-card" key={item.reservaId}><header><strong>{item.codigoReserva}</strong><ReservationBadge status={item.estado} /></header><p>{shortDate.format(parseDate(item.fecha))} · {item.horaProgramada.slice(0, 5)}</p><strong>{item.cliente}</strong><p>{item.servicio} · {item.profesional ?? 'Sin profesional'}</p><footer><span>{item.resultado ?? 'Sin resultado'}</span><Link className="btn btn-sm btn-outline-primary" to={`/organizaciones/${organizacionId}/reservas/${item.reservaId}/atencion`}>Ver atención</Link></footer></article>)}</div><ReportPagination page={data.paginaActual} totalPages={data.totalPaginas} totalItems={data.totalElementos} pageSize={data.tamanoPagina} onPage={pagina => { setDraft(current => ({ ...current, pagina })); setApplied(current => ({ ...current, pagina })) }} onPageSize={tamanoPagina => { setDraft(current => ({ ...current, pagina: 1, tamanoPagina })); setApplied(current => ({ ...current, pagina: 1, tamanoPagina })) }} /></article>}
    </> : null}</div>
}
