import { useEffect, useState, type FormEvent } from 'react'
import { useNavigate } from 'react-router-dom'
import { ApiError } from '../../api/apiClient'
import { descargarArchivo, exportarReporteIngresos, obtenerReporteIngresos } from '../../api/reportesApi'
import type { ReporteIngresosFiltros, ReporteIngresosResponse } from '../../types'
import { DateRangeFilter, EmptyReport, money, parseDate, ReportKpi, ReportLoading, ReportPagination, SelectFilter, shortDate, validateRange, type SelectOption } from './ReportShared'

function defaultRange() { const hasta = new Date(); const desde = new Date(hasta); desde.setDate(desde.getDate() - 29); const local = (date: Date) => new Date(date.getTime() - date.getTimezoneOffset() * 60_000).toISOString().slice(0, 10); return { fechaDesde: local(desde), fechaHasta: local(hasta) } }
const initial = (organizacionId: string): ReporteIngresosFiltros => ({ ...defaultRange(), organizacionId, pagina: 1, tamanoPagina: 10 })

export function IncomeReport({ organizacionId, sedes, metodos }: { organizacionId: string; sedes: SelectOption[]; metodos: SelectOption[] }) {
  const navigate = useNavigate()
  const [draft, setDraft] = useState(() => initial(organizacionId)); const [applied, setApplied] = useState(() => initial(organizacionId))
  const [data, setData] = useState<ReporteIngresosResponse>(); const [loading, setLoading] = useState(true); const [exporting, setExporting] = useState(false)
  const [error, setError] = useState(''); const [validation, setValidation] = useState('')
  useEffect(() => { const next = initial(organizacionId); setDraft(next); setApplied(next) }, [organizacionId])
  useEffect(() => { const controller = new AbortController(); setLoading(true); setError(''); obtenerReporteIngresos(applied, controller.signal).then(setData).catch(caught => { if (controller.signal.aborted) return; if (caught instanceof ApiError && caught.status === 403) return navigate('/acceso-denegado', { replace: true }); setError(caught instanceof Error ? caught.message : 'No se pudo cargar el reporte de ingresos.') }).finally(() => { if (!controller.signal.aborted) setLoading(false) }); return () => controller.abort() }, [applied, navigate])
  const set = <K extends keyof ReporteIngresosFiltros>(key: K, value: ReporteIngresosFiltros[K]) => setDraft(current => ({ ...current, [key]: value }))
  function apply(event: FormEvent) { event.preventDefault(); const message = validateRange(draft.fechaDesde, draft.fechaHasta); setValidation(message); if (!message) setApplied({ ...draft, pagina: 1 }) }
  function clear() { const next = initial(organizacionId); setDraft(next); setValidation(''); setApplied(next) }
  async function exportCsv() { setExporting(true); setError(''); try { const file = await exportarReporteIngresos(applied); descargarArchivo(file.blob, file.filename ?? `reporte-ingresos-${applied.fechaDesde}-${applied.fechaHasta}.csv`) } catch (caught) { if (caught instanceof ApiError && caught.status === 403) return navigate('/acceso-denegado', { replace: true }); setError(caught instanceof ApiError && caught.status === 409 ? 'El reporte contiene demasiados registros. Reduce el rango o aplica más filtros.' : caught instanceof Error ? caught.message : 'No se pudo exportar el reporte.') } finally { setExporting(false) } }
  return <div className="reports-section">
    <form className="report-filters" onSubmit={apply}><DateRangeFilter desde={draft.fechaDesde} hasta={draft.fechaHasta} onDesde={value => set('fechaDesde', value)} onHasta={value => set('fechaHasta', value)} /><SelectFilter label="Sede" value={draft.sedeId} options={sedes} emptyLabel="Todas las sedes" onChange={value => set('sedeId', value || undefined)} /><SelectFilter label="Método de pago" value={draft.metodoPagoId} options={metodos} emptyLabel="Todos los métodos" onChange={value => set('metodoPagoId', value || undefined)} />{validation ? <p className="report-validation">{validation}</p> : null}<div className="report-filter-actions"><button className="btn btn-primary" disabled={loading}>Aplicar filtros</button><button type="button" className="btn btn-outline-secondary" onClick={clear}>Limpiar</button><button type="button" className="btn btn-outline-success" disabled={exporting || loading} onClick={() => void exportCsv()}>{exporting ? 'Generando archivo...' : 'Exportar CSV'}</button></div></form>
    {error ? <div className="alert alert-danger" role="alert">{error}</div> : null}
    {loading ? <ReportLoading /> : data ? <><div className="report-kpis"><ReportKpi label="Ingresos brutos" value={money.format(data.indicadores.ingresosBrutos)} /><ReportKpi label="Reembolsos" value={money.format(data.indicadores.reembolsos)} /><ReportKpi label="Ingresos netos" value={money.format(data.indicadores.ingresosNetos)} /><ReportKpi label="Cantidad de pagos" value={data.indicadores.cantidadPagos} /><ReportKpi label="Ticket promedio" value={data.indicadores.ticketPromedio == null ? '—' : money.format(data.indicadores.ticketPromedio)} /></div>
      {data.elementos.length === 0 ? <EmptyReport>No se encontraron movimientos económicos para este periodo.</EmptyReport> : <article className="report-card"><div className="report-table-wrap"><table className="table table-hover report-table"><thead><tr><th>Fecha</th><th>Código</th><th>Reserva</th><th>Cliente</th><th>Sede</th><th>Tipo</th><th>Método</th><th>Operación</th><th>Monto</th></tr></thead><tbody>{data.elementos.map((item, index) => <tr key={`${item.codigoMovimiento}-${index}`}><td>{shortDate.format(parseDate(item.fecha))}</td><td>{item.codigoMovimiento}</td><td>{item.codigoReserva}</td><td>{item.cliente}</td><td>{item.sede}</td><td><span className={`badge ${item.tipo === 'Pago' ? 'text-bg-success' : 'text-bg-warning'}`}>{item.tipo}</span></td><td>{item.metodo ?? '—'}</td><td>{item.numeroOperacion ?? '—'}</td><td className={item.tipo === 'Reembolso' ? 'text-danger' : ''}>{money.format(item.monto)}</td></tr>)}</tbody></table></div><div className="report-mobile-list">{data.elementos.map((item, index) => <article className="report-card report-mobile-card" key={`${item.codigoMovimiento}-${index}`}><header><strong>{item.codigoMovimiento}</strong><span className={`badge ${item.tipo === 'Pago' ? 'text-bg-success' : 'text-bg-warning'}`}>{item.tipo}</span></header><p>{shortDate.format(parseDate(item.fecha))} · {item.codigoReserva}</p><strong>{item.cliente}</strong><p>{item.sede} · {item.metodo ?? 'Sin método'}</p><footer><span>{item.numeroOperacion ?? 'Sin operación'}</span><strong className={item.tipo === 'Reembolso' ? 'text-danger' : ''}>{money.format(item.monto)}</strong></footer></article>)}</div><ReportPagination page={data.paginaActual} totalPages={data.totalPaginas} totalItems={data.totalElementos} pageSize={data.tamanoPagina} onPage={pagina => { setDraft(current => ({ ...current, pagina })); setApplied(current => ({ ...current, pagina })) }} onPageSize={tamanoPagina => { setDraft(current => ({ ...current, pagina: 1, tamanoPagina })); setApplied(current => ({ ...current, pagina: 1, tamanoPagina })) }} /></article>}
    </> : null}
  </div>
}
