import { useCallback, useEffect, useState, type FormEvent } from 'react'
import { Link, useNavigate, useParams } from 'react-router-dom'
import { listCategoryOptions } from '../../api/categoriasApi'
import * as api from '../../api/serviciosApi'
import { Empty, ErrorAlert, Loading, StatusBadge, SuccessAlert } from '../../components/common/Feedback'
import { Pagination } from '../../components/tables/Pagination'
import type { EstadoFiltro, ModalidadServicio, Option, PageResult, SedeAsignacion, Servicio, ServicioRequest } from '../../types'

const modalities: ModalidadServicio[] = ['Presencial', 'Virtual', 'Domicilio']
const emptyForm: ServicioRequest = { categoriaServicioId: '', nombre: '', descripcion: '', duracionMinutos: 30, precio: 0, montoAdelanto: 0, modalidad: 'Presencial', esGrupal: false, capacidadMaxima: 1, requiereProfesional: true, requiereRecurso: false, permiteCancelacion: true, permiteReprogramacion: true, horasLimiteCancelacion: 24, tiempoPreparacionMinutos: 0, tiempoPosteriorMinutos: 0, sedes: [] }

export function ServicesPage() {
  const { organizationId = '' } = useParams(); const [data, setData] = useState<PageResult<Servicio>>(); const [categories, setCategories] = useState<Option[]>([]); const [error, setError] = useState<unknown>()
  const [search, setSearch] = useState(''); const [category, setCategory] = useState(''); const [modality, setModality] = useState<ModalidadServicio | ''>(''); const [state, setState] = useState<EstadoFiltro>('Todos'); const [page, setPage] = useState(1)
  useEffect(() => { void listCategoryOptions(organizationId).then(setCategories).catch(setError) }, [organizationId])
  useEffect(() => { const controller = new AbortController(); api.listServices(organizationId, { busqueda: search, categoriaServicioId: category, modalidad: modality, estado: state, pagina: page }, controller.signal).then().catch(e => { if (e.name !== 'AbortError') setError(e) }); return () => controller.abort() }, [organizationId, search, category, modality, state, page])
  return <><div className="d-flex justify-content-between"><div><h1>Servicios</h1><p className="text-secondary">Servicios y asignaciones por sede.</p></div><Link className="btn btn-primary align-self-start" to="nuevo">Nuevo servicio</Link></div><div className="card card-body mb-3"><div className="row g-2"><div className="col-lg-4"><input className="form-control" placeholder="Buscar servicio" value={search} onChange={e => { setSearch(e.target.value); setPage(1) }} /></div><div className="col-lg-3"><select className="form-select" value={category} onChange={e => { setCategory(e.target.value); setPage(1) }}><option value="">Todas las categorías</option>{categories.map(item => <option key={item.id} value={item.id}>{item.nombre}</option>)}</select></div><div className="col-lg-3"><select className="form-select" value={modality} onChange={e => { setModality(e.target.value as ModalidadServicio | ''); setPage(1) }}><option value="">Todas las modalidades</option>{modalities.map(item => <option key={item}>{item}</option>)}</select></div><div className="col-lg-2"><select className="form-select" value={state} onChange={e => { setState(e.target.value as EstadoFiltro); setPage(1) }}><option>Todos</option><option>Activos</option><option>Inactivos</option></select></div></div></div>
    {error ? <ErrorAlert error={error} /> : !data ? <Loading /> : data.elementos.length === 0 ? <Empty /> : <div className="card table-responsive"><table className="table table-hover mb-0"><thead><tr><th>Nombre</th><th>Categoría</th><th>Modalidad</th><th>Precio</th><th>Capacidad</th><th>Sedes</th><th>Estado</th><th /></tr></thead><tbody>{data.elementos.map(item => <tr key={item.id}><td>{item.nombre}</td><td>{item.categoria}</td><td>{item.modalidad}</td><td>S/ {item.precio.toFixed(2)}</td><td>{item.esGrupal ? `Grupal (${item.capacidadMaxima})` : 'Individual'}</td><td>{item.cantidadSedes}</td><td><StatusBadge active={item.estaActivo} /></td><td><Link className="btn btn-sm btn-outline-primary" to={`/servicios/${item.id}`}>Ver</Link></td></tr>)}</tbody></table></div>}
    {data ? <div className="mt-3"><Pagination page={data.paginaActual} total={data.totalPaginas} onChange={setPage} /></div> : null}<Link className="btn btn-link" to={`/organizaciones/${organizationId}`}>Volver</Link></>
}

export function ServiceFormPage() {
  const { organizationId: routeOrganizationId, id } = useParams(); const navigate = useNavigate(); const [organizationId, setOrganizationId] = useState(routeOrganizationId ?? '')
  const [form, setForm] = useState<ServicioRequest>(emptyForm); const [categories, setCategories] = useState<Option[]>([]); const [availableSedes, setAvailableSedes] = useState<SedeAsignacion[]>([])
  const [loading, setLoading] = useState(true); const [busy, setBusy] = useState(false); const [error, setError] = useState<unknown>()
  useEffect(() => { async function load() { let orgId = routeOrganizationId ?? ''; let detail: Servicio | undefined; if (id) { detail = await api.getService(id); orgId = detail.organizacionId; setOrganizationId(orgId) } const [categoryOptions, sedes] = await Promise.all([listCategoryOptions(orgId), api.listServiceSedes(orgId, id)]); setCategories(categoryOptions); setAvailableSedes(sedes); if (detail) setForm({ categoriaServicioId: detail.categoriaServicioId ?? '', nombre: detail.nombre, descripcion: detail.descripcion, duracionMinutos: detail.duracionMinutos, precio: detail.precio, montoAdelanto: detail.montoAdelanto, modalidad: detail.modalidad, esGrupal: detail.esGrupal, capacidadMaxima: detail.capacidadMaxima, requiereProfesional: detail.requiereProfesional ?? false, requiereRecurso: detail.requiereRecurso ?? false, permiteCancelacion: detail.permiteCancelacion ?? false, permiteReprogramacion: detail.permiteReprogramacion ?? false, horasLimiteCancelacion: detail.horasLimiteCancelacion ?? 0, tiempoPreparacionMinutos: detail.tiempoPreparacionMinutos ?? 0, tiempoPosteriorMinutos: detail.tiempoPosteriorMinutos ?? 0, sedes: detail.sedes?.map(sede => ({ sedeId: sede.sedeId, precioEspecial: sede.precioEspecial })) ?? [] }); else setForm(emptyForm) } void load().catch(setError).finally(() => setLoading(false)) }, [id, routeOrganizationId])
  function value<K extends keyof ServicioRequest>(name: K, fieldValue: ServicioRequest[K]) { setForm(current => ({ ...current, [name]: fieldValue })) }
  function toggleSede(sedeId: string, checked: boolean) { value('sedes', checked ? [...form.sedes, { sedeId }] : form.sedes.filter(item => item.sedeId !== sedeId)) }
  function sedePrice(sedeId: string, price: string) { value('sedes', form.sedes.map(item => item.sedeId === sedeId ? { ...item, precioEspecial: price === '' ? undefined : Number(price) } : item)) }
  async function submit(event: FormEvent) { event.preventDefault(); setError(undefined); if (form.montoAdelanto > form.precio) { setError(new Error('El adelanto no puede superar el precio.')); return } if (!form.esGrupal && form.capacidadMaxima !== 1) { setError(new Error('Un servicio individual debe tener capacidad uno.')); return } setBusy(true); try { if (id) { await api.updateService(id, form); navigate(`/servicios/${id}`) } else { const created = await api.createService(organizationId, form); navigate(`/servicios/${created.id}`) } } catch (caught) { setError(caught) } finally { setBusy(false) } }
  if (loading) return <Loading />
  return <><h1>{id ? 'Editar servicio' : 'Nuevo servicio'}</h1>{error ? <ErrorAlert error={error} /> : null}<form className="card card-body" onSubmit={submit}><div className="row g-3">
    <div className="col-md-6"><label className="form-label">Categoría</label><select required className="form-select" value={form.categoriaServicioId} onChange={e => value('categoriaServicioId', e.target.value)}><option value="">Selecciona…</option>{categories.map(item => <option key={item.id} value={item.id}>{item.nombre}</option>)}</select></div><div className="col-md-6"><label className="form-label">Nombre</label><input required className="form-control" value={form.nombre} onChange={e => value('nombre', e.target.value)} /></div>
    <div className="col-12"><label className="form-label">Descripción</label><textarea className="form-control" value={form.descripcion ?? ''} onChange={e => value('descripcion', e.target.value)} /></div>
    <NumberField label="Duración (minutos)" value={form.duracionMinutos} onChange={number => value('duracionMinutos', number)} min={1} /><NumberField label="Precio" value={form.precio} onChange={number => value('precio', number)} min={0} step="0.01" /><NumberField label="Adelanto" value={form.montoAdelanto} onChange={number => value('montoAdelanto', number)} min={0} step="0.01" />
    <div className="col-md-3"><label className="form-label">Modalidad</label><select className="form-select" value={form.modalidad} onChange={e => value('modalidad', e.target.value as ModalidadServicio)}>{modalities.map(item => <option key={item}>{item}</option>)}</select></div>
    <div className="col-md-3 form-check-wrap"><label className="form-check"><input className="form-check-input" type="checkbox" checked={form.esGrupal} onChange={e => { value('esGrupal', e.target.checked); if (!e.target.checked) value('capacidadMaxima', 1) }} /> Grupal</label></div><NumberField label="Capacidad" value={form.capacidadMaxima} onChange={number => value('capacidadMaxima', number)} min={1} disabled={!form.esGrupal} />
    <NumberField label="Límite cancelación (h)" value={form.horasLimiteCancelacion} onChange={number => value('horasLimiteCancelacion', number)} min={0} /><NumberField label="Preparación (min)" value={form.tiempoPreparacionMinutos} onChange={number => value('tiempoPreparacionMinutos', number)} min={0} /><NumberField label="Tiempo posterior (min)" value={form.tiempoPosteriorMinutos} onChange={number => value('tiempoPosteriorMinutos', number)} min={0} />
    <div className="col-12 d-flex flex-wrap gap-4">{(['requiereProfesional','requiereRecurso','permiteCancelacion','permiteReprogramacion'] as const).map(name => <label className="form-check" key={name}><input type="checkbox" className="form-check-input" checked={form[name]} onChange={e => value(name, e.target.checked)} /> {name.replace(/([A-Z])/g, ' $1')}</label>)}</div>
    <div className="col-12"><h2 className="h5">Sedes y precio especial</h2>{availableSedes.length === 0 ? <Empty message="No hay sedes activas disponibles." /> : availableSedes.map(sede => { const selected = form.sedes.find(item => item.sedeId === sede.sedeId); return <div className="row align-items-center border-top py-2" key={sede.sedeId}><div className="col-md-7"><label><input className="form-check-input me-2" type="checkbox" checked={Boolean(selected)} onChange={e => toggleSede(sede.sedeId, e.target.checked)} />{sede.nombre}</label></div><div className="col-md-5"><input className="form-control" type="number" min="0" step="0.01" disabled={!selected} placeholder="Precio especial opcional" value={selected?.precioEspecial ?? ''} onChange={e => sedePrice(sede.sedeId, e.target.value)} /></div></div> })}</div>
  </div><div className="d-flex gap-2 mt-4"><button disabled={busy} className="btn btn-primary">{busy ? 'Guardando…' : 'Guardar'}</button><button type="button" className="btn btn-outline-secondary" onClick={() => navigate(-1)}>Cancelar</button></div></form></>
}

function NumberField({ label, value, onChange, min, step = '1', disabled = false }: { label: string; value: number; onChange: (value: number) => void; min: number; step?: string; disabled?: boolean }) { return <div className="col-md-3"><label className="form-label">{label}</label><input required className="form-control" type="number" value={value} min={min} step={step} disabled={disabled} onChange={e => onChange(Number(e.target.value))} /></div> }

export function ServiceDetailPage() {
  const { id = '' } = useParams(); const navigate = useNavigate(); const [item, setItem] = useState<Servicio>(); const [error, setError] = useState<unknown>(); const [message, setMessage] = useState('')
  const load = useCallback(async () => { setItem(await api.getService(id)) }, [id])
  useEffect(() => { void load().catch(setError) }, [load])
  async function action(kind: 'toggle' | 'delete') { if (!confirm(kind === 'delete' ? '¿Eliminar lógicamente este servicio?' : '¿Cambiar su estado?')) return; try { if (kind === 'delete') { await api.deleteService(id); navigate(`/organizaciones/${item?.organizacionId}/servicios`) } else { await api.toggleService(id); setMessage('Estado actualizado.'); await load() } } catch (caught) { setError(caught) } }
  if (error) return <ErrorAlert error={error} />; if (!item) return <Loading />
  return <><SuccessAlert message={message} /><div className="d-flex justify-content-between"><div><h1>{item.nombre}</h1><p className="text-secondary">{item.organizacion} · {item.categoria}</p><StatusBadge active={item.estaActivo} /></div><Link className="btn btn-primary align-self-start" to="editar">Editar</Link></div><div className="card card-body my-3"><div className="row"><p className="col-md-4"><strong>Modalidad:</strong> {item.modalidad}</p><p className="col-md-4"><strong>Duración:</strong> {item.duracionMinutos} min</p><p className="col-md-4"><strong>Capacidad:</strong> {item.capacidadMaxima}</p><p className="col-md-4"><strong>Precio:</strong> S/ {item.precio.toFixed(2)}</p><p className="col-md-4"><strong>Adelanto:</strong> S/ {item.montoAdelanto.toFixed(2)}</p></div><h2 className="h5">Sedes</h2>{item.sedes?.length ? <ul>{item.sedes.map(sede => <li key={sede.sedeId}>{sede.sede} — S/ {(sede.precioAplicable ?? item.precio).toFixed(2)}</li>)}</ul> : <p>Sin sedes asignadas.</p>}</div><div className="d-flex gap-2"><button className="btn btn-outline-warning" onClick={() => void action('toggle')}>{item.estaActivo ? 'Desactivar' : 'Activar'}</button><button className="btn btn-outline-danger" onClick={() => void action('delete')}>Eliminar</button><Link className="btn btn-link" to={`/organizaciones/${item.organizacionId}/servicios`}>Volver</Link></div></>
}
