import { useCallback, useEffect, useState, type FormEvent } from 'react'
import { Link, useNavigate, useParams } from 'react-router-dom'
import * as api from '../../api/recursosApi'
import { listServices } from '../../api/serviciosApi'
import { Empty, ErrorAlert, Loading, StatusBadge } from '../../components/common/Feedback'
import { Pagination } from '../../components/tables/Pagination'
import type { EstadoFiltro, Servicio } from '../../types'

const empty: api.RecursoRequest = { nombre: '', codigo: '', descripcion: '', tipoRecurso: '', capacidad: 1, ubicacionInterna: '', observaciones: '', servicios: [] }

export function RecursosPage() {
  const { organizationId = '', sedeId = '' } = useParams(); const [data, setData] = useState<Awaited<ReturnType<typeof api.listarRecursos>>>(); const [error, setError] = useState<unknown>(); const [search, setSearch] = useState(''); const [state, setState] = useState<EstadoFiltro>('Todos'); const [page, setPage] = useState(1)
  useEffect(() => { const c = new AbortController(); api.listarRecursos(sedeId, { busqueda: search, estado: state, pagina: page, tamanoPagina: 10 }, c.signal).then(setData).catch(e => { if (e.name !== 'AbortError') setError(e) }); return () => c.abort() }, [sedeId, search, state, page])
  return <><div className="d-flex justify-content-between mb-3"><div><h1>Recursos</h1><p className="text-secondary">Equipos, ambientes y otros recursos de la sede.</p></div><Link className="btn btn-primary align-self-start" to="nuevo">Nuevo recurso</Link></div><div className="card card-body mb-3"><div className="row g-2"><div className="col-md-8"><input className="form-control" placeholder="Buscar recurso" value={search} onChange={e => { setSearch(e.target.value); setPage(1) }} /></div><div className="col-md-4"><select className="form-select" value={state} onChange={e => { setState(e.target.value as EstadoFiltro); setPage(1) }}><option>Todos</option><option>Activos</option><option>Inactivos</option></select></div></div></div>{error ? <ErrorAlert error={error} /> : !data ? <Loading /> : data.elementos.length === 0 ? <Empty /> : <div className="card"><div className="table-responsive"><table className="table table-hover mb-0"><thead><tr><th>Nombre</th><th>Código</th><th>Tipo</th><th>Capacidad</th><th>Servicios</th><th>Estado</th><th /></tr></thead><tbody>{data.elementos.map(r => <tr key={r.id}><td>{r.nombre}</td><td>{r.codigo || '—'}</td><td>{r.tipoRecurso}</td><td>{r.capacidad}</td><td>{r.serviciosCount}</td><td><StatusBadge active={r.estaActivo} /></td><td className="text-end"><Link className="btn btn-sm btn-outline-primary" to={r.id}>Ver</Link></td></tr>)}</tbody></table></div></div>}{data && <div className="mt-3"><Pagination page={data.paginaActual} total={data.totalPaginas} onChange={setPage} /></div>}<Link className="btn btn-link px-0 mt-2" to={`/organizaciones/${organizationId}/sedes`}>Volver a sedes</Link></>
}

export function RecursoFormPage() {
  const { organizationId = '', sedeId = '', id } = useParams(); const navigate = useNavigate(); const [form, setForm] = useState<api.RecursoRequest>(empty); const [services, setServices] = useState<Servicio[]>([]); const [loading, setLoading] = useState(Boolean(id)); const [busy, setBusy] = useState(false); const [error, setError] = useState<unknown>()
  useEffect(() => { Promise.all([listServices(organizationId, { estado: 'Activos', pagina: 1, tamanoPagina: 100 }), id ? api.obtenerRecurso(id) : Promise.resolve(undefined)]).then(([sp, item]) => { setServices(sp.elementos); if (item) setForm({ nombre: item.nombre, codigo: item.codigo ?? '', descripcion: item.descripcion ?? '', tipoRecurso: item.tipoRecurso, capacidad: item.capacidad, ubicacionInterna: item.ubicacionInterna ?? '', observaciones: item.observaciones ?? '', servicios: item.servicios.filter(s => s.estaActivo).map(s => ({ servicioId: s.servicioId, esObligatorio: s.esObligatorio, cantidadRequerida: s.cantidadRequerida })) }) }).catch(setError).finally(() => setLoading(false)) }, [organizationId, id])
  function toggle(serviceId: string) { setForm(current => { const list = current.servicios ?? []; const exists = list.some(x => x.servicioId === serviceId); return { ...current, servicios: exists ? list.filter(x => x.servicioId !== serviceId) : [...list, { servicioId, esObligatorio: true, cantidadRequerida: 1 }] } }) }
  async function submit(e: FormEvent) { e.preventDefault(); setBusy(true); setError(undefined); try { if (id) { await api.actualizarRecurso(id, form); await api.reemplazarServiciosRecurso(id, form.servicios ?? []); navigate(`../${id}`) } else { const created = await api.crearRecurso(sedeId, form); navigate(`../${created.id}`) } } catch (caught) { setError(caught) } finally { setBusy(false) } }
  if (loading) return <Loading />
  return <><h1>{id ? 'Editar recurso' : 'Nuevo recurso'}</h1>{error ? <ErrorAlert error={error} /> : null}<form className="card card-body" onSubmit={submit}><div className="row g-3"><div className="col-md-6"><label className="form-label">Nombre</label><input required className="form-control" value={form.nombre} onChange={e => setForm({ ...form, nombre: e.target.value })} /></div><div className="col-md-3"><label className="form-label">Código</label><input className="form-control" value={form.codigo ?? ''} onChange={e => setForm({ ...form, codigo: e.target.value })} /></div><div className="col-md-3"><label className="form-label">Capacidad</label><input required min="1" type="number" className="form-control" value={form.capacidad} onChange={e => setForm({ ...form, capacidad: Number(e.target.value) })} /></div><div className="col-md-6"><label className="form-label">Tipo de recurso</label><input required className="form-control" placeholder="Ej. Consultorio, equipo, cancha" value={form.tipoRecurso} onChange={e => setForm({ ...form, tipoRecurso: e.target.value })} /></div><div className="col-md-6"><label className="form-label">Ubicación interna</label><input className="form-control" value={form.ubicacionInterna ?? ''} onChange={e => setForm({ ...form, ubicacionInterna: e.target.value })} /></div><div className="col-12"><label className="form-label">Descripción</label><textarea className="form-control" value={form.descripcion ?? ''} onChange={e => setForm({ ...form, descripcion: e.target.value })} /></div><div className="col-12"><label className="form-label d-block">Servicios asociados</label><div className="d-flex flex-wrap gap-2">{services.map(s => <label key={s.id} className="border rounded px-3 py-2"><input className="form-check-input me-2" type="checkbox" checked={(form.servicios ?? []).some(x => x.servicioId === s.id)} onChange={() => toggle(s.id)} />{s.nombre}</label>)}</div></div></div><div className="mt-4 d-flex gap-2"><button disabled={busy} className="btn btn-primary">Guardar</button><button type="button" className="btn btn-outline-secondary" onClick={() => navigate(-1)}>Cancelar</button></div></form></>
}

export function RecursoDetailPage() {
  const { id = '' } = useParams(); const navigate = useNavigate(); const [item, setItem] = useState<api.RecursoDetalle>(); const [error, setError] = useState<unknown>()
  const load = useCallback(() => api.obtenerRecurso(id).then(setItem).catch(setError), [id]); useEffect(() => { void load() }, [load])
  async function toggle() { if (!item) return; try { await api.cambiarEstadoRecurso(id, !item.estaActivo); await load() } catch (e) { setError(e) } }
  async function remove() { if (!confirm('¿Eliminar lógicamente este recurso?')) return; try { await api.eliminarRecurso(id); navigate('..') } catch (e) { setError(e) } }
  if (error) return <ErrorAlert error={error} />; if (!item) return <Loading />
  return <><div className="d-flex justify-content-between"><div><h1>{item.nombre}</h1><StatusBadge active={item.estaActivo} /></div><Link className="btn btn-primary align-self-start" to="editar">Editar</Link></div><div className="card card-body my-3"><dl className="row mb-0"><dt className="col-sm-3">Sede</dt><dd className="col-sm-9">{item.sedeNombre}</dd><dt className="col-sm-3">Tipo</dt><dd className="col-sm-9">{item.tipoRecurso}</dd><dt className="col-sm-3">Capacidad</dt><dd className="col-sm-9">{item.capacidad}</dd><dt className="col-sm-3">Servicios</dt><dd className="col-sm-9">{item.servicios.filter(s => s.estaActivo).map(s => s.servicioNombre).join(', ') || '—'}</dd></dl></div><div className="d-flex gap-2"><button className="btn btn-outline-warning" onClick={() => void toggle()}>{item.estaActivo ? 'Desactivar' : 'Activar'}</button><button className="btn btn-outline-danger" onClick={() => void remove()}>Eliminar</button><button className="btn btn-link" onClick={() => navigate(-1)}>Volver</button></div></>
}
