import { useCallback, useEffect, useState, type FormEvent } from 'react'
import { Link, useNavigate, useParams } from 'react-router-dom'
import * as api from '../../api/clientesActualApi'
import { Empty, ErrorAlert, Loading, StatusBadge } from '../../components/common/Feedback'
import { Pagination } from '../../components/tables/Pagination'
import type { EstadoFiltro } from '../../types'

const empty: api.ClienteRequest = { tipoDocumento: 'DNI', numeroDocumento: '', nombres: '', apellidos: '', correo: '', telefono: '', direccion: '', fechaNacimiento: null, observaciones: '' }

export function ClientesActualPage() {
  const { organizationId = '' } = useParams(); const [data,setData]=useState<Awaited<ReturnType<typeof api.listarClientesActual>>>(); const [error,setError]=useState<unknown>(); const [search,setSearch]=useState(''); const [state,setState]=useState<EstadoFiltro>('Todos'); const [page,setPage]=useState(1)
  useEffect(()=>{const c=new AbortController();api.listarClientesActual(organizationId,{busqueda:search,estado:state,pagina:page,tamanoPagina:10},c.signal).then(setData).catch(e=>{if(e.name!=='AbortError')setError(e)});return()=>c.abort()},[organizationId,search,state,page])
  return <section><div className="d-flex justify-content-between mb-3"><div><h1>Clientes</h1><p className="text-secondary">Clientes registrados en la organización.</p></div><Link className="btn btn-primary align-self-start" to="nuevo">Nuevo cliente</Link></div><div className="card card-body mb-3"><div className="row g-2"><div className="col-md-8"><input className="form-control" placeholder="Buscar por nombre o documento" value={search} onChange={e=>{setSearch(e.target.value);setPage(1)}}/></div><div className="col-md-4"><select className="form-select" value={state} onChange={e=>{setState(e.target.value as EstadoFiltro);setPage(1)}}><option>Todos</option><option>Activos</option><option>Inactivos</option></select></div></div></div>{error?<ErrorAlert error={error}/>:!data?<Loading/>:data.elementos.length===0?<Empty/>:<div className="card"><div className="table-responsive"><table className="table table-hover mb-0"><thead><tr><th>Cliente</th><th>Documento</th><th>Contacto</th><th>Estado</th><th/></tr></thead><tbody>{data.elementos.map(x=><tr key={x.id}><td>{x.nombreCompleto}</td><td>{x.tipoDocumento} {x.numeroDocumento}</td><td>{x.correo||x.telefono||'—'}</td><td><StatusBadge active={x.estaActivo}/></td><td className="text-end"><Link className="btn btn-sm btn-outline-primary" to={x.id}>Ver</Link></td></tr>)}</tbody></table></div></div>}{data?<div className="mt-3"><Pagination page={data.paginaActual} total={data.totalPaginas} onChange={setPage}/></div>:null}</section>
}

export function ClienteActualFormPage() {
  const { organizationId='', id }=useParams(); const navigate=useNavigate(); const [form,setForm]=useState<api.ClienteRequest>(empty); const [loading,setLoading]=useState(Boolean(id)); const [busy,setBusy]=useState(false); const [error,setError]=useState<unknown>()
  useEffect(()=>{if(!id)return;api.obtenerClienteActual(id).then(x=>setForm({tipoDocumento:x.tipoDocumento,numeroDocumento:x.numeroDocumento,nombres:x.nombres,apellidos:x.apellidos,correo:x.correo,direccion:x.direccion,telefono:x.telefono,fechaNacimiento:x.fechaNacimiento,observaciones:x.observaciones})).catch(setError).finally(()=>setLoading(false))},[id])
  async function submit(e:FormEvent){e.preventDefault();setBusy(true);setError(undefined);try{if(id){await api.actualizarClienteActual(id,form);navigate(`../${id}`)}else{const created=await api.crearClienteActual(organizationId,form);navigate(`../${created.id}`)}}catch(caught){setError(caught)}finally{setBusy(false)}}
  if(loading)return <Loading/>
  return <section><h1>{id?'Editar cliente':'Nuevo cliente'}</h1>{error?<ErrorAlert error={error}/>:null}<form className="card card-body" onSubmit={submit}><div className="row g-3"><div className="col-md-3"><label className="form-label">Tipo documento</label><select className="form-select" value={form.tipoDocumento} onChange={e=>setForm({...form,tipoDocumento:e.target.value as api.TipoDocumentoCliente})}><option>DNI</option><option value="CarnetExtranjeria">Carnet extranjería</option><option>Pasaporte</option><option>RUC</option></select></div><div className="col-md-3"><label className="form-label">Número</label><input required className="form-control" value={form.numeroDocumento} onChange={e=>setForm({...form,numeroDocumento:e.target.value})}/></div><div className="col-md-3"><label className="form-label">Nombres</label><input required className="form-control" value={form.nombres} onChange={e=>setForm({...form,nombres:e.target.value})}/></div><div className="col-md-3"><label className="form-label">Apellidos</label><input required className="form-control" value={form.apellidos} onChange={e=>setForm({...form,apellidos:e.target.value})}/></div><div className="col-md-4"><label className="form-label">Correo</label><input type="email" className="form-control" value={form.correo??''} onChange={e=>setForm({...form,correo:e.target.value})}/></div><div className="col-md-4"><label className="form-label">Teléfono</label><input className="form-control" value={form.telefono??''} onChange={e=>setForm({...form,telefono:e.target.value})}/></div><div className="col-md-4"><label className="form-label">Fecha nacimiento</label><input type="date" className="form-control" value={form.fechaNacimiento??''} onChange={e=>setForm({...form,fechaNacimiento:e.target.value||null})}/></div><div className="col-12"><label className="form-label">Dirección</label><input className="form-control" value={form.direccion??''} onChange={e=>setForm({...form,direccion:e.target.value})}/></div><div className="col-12"><label className="form-label">Observaciones</label><textarea className="form-control" value={form.observaciones??''} onChange={e=>setForm({...form,observaciones:e.target.value})}/></div></div><div className="d-flex gap-2 mt-4"><button disabled={busy} className="btn btn-primary">Guardar</button><button type="button" className="btn btn-outline-secondary" onClick={()=>navigate(-1)}>Cancelar</button></div></form></section>
}

export function ClienteActualDetailPage() {
  const { id='' }=useParams(); const navigate=useNavigate(); const [item,setItem]=useState<api.ClienteDetalle>(); const [error,setError]=useState<unknown>()
  const load=useCallback(()=>api.obtenerClienteActual(id).then(setItem),[id]);useEffect(()=>{void load().catch(setError)},[load])
  async function toggle(){if(!item)return;try{await api.cambiarEstadoClienteActual(id,!item.estaActivo);await load()}catch(caught){setError(caught)}}
  async function remove(){if(!item||!confirm('¿Eliminar lógicamente este cliente?'))return;try{await api.eliminarClienteActual(id);navigate('..')}catch(caught){setError(caught)}}
  if(error)return <ErrorAlert error={error}/>;if(!item)return <Loading/>
  return <section><div className="d-flex justify-content-between"><div><h1>{item.nombreCompleto}</h1><StatusBadge active={item.estaActivo}/></div><Link className="btn btn-primary" to="editar">Editar</Link></div><div className="card card-body my-3"><dl className="row mb-0"><dt className="col-sm-3">Documento</dt><dd className="col-sm-9">{item.tipoDocumento} {item.numeroDocumento}</dd><dt className="col-sm-3">Correo</dt><dd className="col-sm-9">{item.correo||'—'}</dd><dt className="col-sm-3">Teléfono</dt><dd className="col-sm-9">{item.telefono||'—'}</dd><dt className="col-sm-3">Dirección</dt><dd className="col-sm-9">{item.direccion||'—'}</dd></dl></div><div className="d-flex gap-2"><button className="btn btn-outline-warning" onClick={()=>void toggle()}>{item.estaActivo?'Desactivar':'Activar'}</button><button className="btn btn-outline-danger" onClick={()=>void remove()}>Eliminar</button><button className="btn btn-link" onClick={()=>navigate(-1)}>Volver</button></div></section>
}
